-- 2개월치 학습 커리큘럼 (112개, 영역 인터리빙)
-- display_order 100부터 시작 — V2 시드(1~3)가 먼저 소진된 뒤 이어짐
INSERT INTO curriculum_topics (id, area, title, mode, display_order, generated)
VALUES
  (gen_random_uuid(), 'SYSTEM_DESIGN', '채팅 시스템 설계 — WebSocket·메시지 순서·읽음 확인', 'DESIGN', 100, false),
  (gen_random_uuid(), 'LOGISTICS', 'WMS 입고 프로세스 — ASN·검수·적치 전략', 'CONCEPT', 101, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Idempotency 설계 총정리 — 키·저장소·소비자 멱등성', 'CONCEPT', 102, false),
  (gen_random_uuid(), 'BACKEND_DEV', '@Transactional 동작 원리와 함정 8가지', 'CONCEPT', 103, false),
  (gen_random_uuid(), 'DATABASE', '복합 인덱스 설계와 커버링 인덱스', 'CONCEPT', 104, false),
  (gen_random_uuid(), 'INFRA', 'Docker 이미지 최적화 — 멀티스테이지·레이어 캐시', 'CONCEPT', 105, false),
  (gen_random_uuid(), 'CS', 'HTTP/2·HTTP/3와 성능', 'CONCEPT', 106, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '알림 시스템 설계 — 푸시·재시도·중복 제거', 'DESIGN', 107, false),
  (gen_random_uuid(), 'LOGISTICS', '피킹 최적화 심화 — Batch·Zone·Wave·Cluster', 'CONCEPT', 108, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Event Sourcing 기초와 도입 판단', 'CONCEPT', 109, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'JPA N+1 문제와 해결 전략', 'CONCEPT', 110, false),
  (gen_random_uuid(), 'DATABASE', 'MVCC 내부 — MySQL vs PostgreSQL', 'CONCEPT', 111, false),
  (gen_random_uuid(), 'INFRA', 'K8s 리소스 관리 — requests/limits·QoS·OOMKilled', 'CONCEPT', 112, false),
  (gen_random_uuid(), 'CS', 'TLS 핸드셰이크와 mTLS', 'CONCEPT', 113, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '검색 자동완성 설계 — Trie·랭킹·트래픽 급증', 'DESIGN', 114, false),
  (gen_random_uuid(), 'LOGISTICS', '재고 실사와 Cycle Counting', 'CONCEPT', 115, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'CQRS 실전 — 읽기 모델 동기화 전략', 'CONCEPT', 116, false),
  (gen_random_uuid(), 'BACKEND_DEV', '낙관적 락 재시도 구현 — Spring Retry', 'CONCEPT', 117, false),
  (gen_random_uuid(), 'DATABASE', '격리수준과 이상현상 — 실습 시나리오', 'CONCEPT', 118, false),
  (gen_random_uuid(), 'INFRA', 'K8s 배포 전략 실전 — Canary·Argo Rollouts', 'CONCEPT', 119, false),
  (gen_random_uuid(), 'CS', 'JVM GC 알고리즘 — G1·ZGC', 'CONCEPT', 120, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 Key-Value Store 설계 — 복제·일관성 해싱·충돌 해결', 'DESIGN', 121, false),
  (gen_random_uuid(), 'LOGISTICS', '주문 할당(Allocation) 전략 — 창고 선택·분할출고', 'CONCEPT', 122, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'DDD Aggregate 설계 규칙', 'CONCEPT', 123, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'Kafka Consumer 멱등 처리 구현', 'CONCEPT', 124, false),
  (gen_random_uuid(), 'DATABASE', '락 심화 — Gap Lock·Next-key Lock·데드락 분석', 'CONCEPT', 125, false),
  (gen_random_uuid(), 'INFRA', 'Terraform 기초 — 상태 관리·모듈화', 'CONCEPT', 126, false),
  (gen_random_uuid(), 'CS', 'OS 스케줄링과 컨텍스트 스위치 비용', 'CONCEPT', 127, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 ID 생성기 — Snowflake·UUID v7 비교', 'CONCEPT', 128, false),
  (gen_random_uuid(), 'LOGISTICS', 'Cut-off와 새벽배송 SLA 설계', 'CONCEPT', 129, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Bounded Context 나누기 — 이커머스 실습', 'CONCEPT', 130, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'Outbox 릴레이 구현 — Polling vs Debezium', 'CONCEPT', 131, false),
  (gen_random_uuid(), 'DATABASE', '파티셔닝 전략 — Range·List·Hash', 'CONCEPT', 132, false),
  (gen_random_uuid(), 'INFRA', 'GitHub Actions CI/CD 패턴', 'CONCEPT', 133, false),
  (gen_random_uuid(), 'CS', 'I/O 모델 — epoll·io_uring·이벤트 루프', 'CONCEPT', 134, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '웹 크롤러 설계 — 정중함·중복 URL·분산 큐', 'DESIGN', 135, false),
  (gen_random_uuid(), 'LOGISTICS', '라스트마일 배차 — VRP 기초와 휴리스틱', 'CONCEPT', 136, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '헥사고날 아키텍처 — Ports & Adapters', 'CONCEPT', 137, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'Spring 비동기 — @Async·CompletableFuture·Virtual Thread', 'CONCEPT', 138, false),
  (gen_random_uuid(), 'DATABASE', '샤딩 실전 — 키 선택과 리샤딩', 'CONCEPT', 139, false),
  (gen_random_uuid(), 'INFRA', '리버스 프록시와 TLS 종료 — Nginx·Caddy', 'CONCEPT', 140, false),
  (gen_random_uuid(), 'CS', '개발자를 위한 해시·암호화 기초', 'CONCEPT', 141, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '동영상 스트리밍 설계 — 인코딩 파이프라인·적응형 스트리밍', 'DESIGN', 142, false),
  (gen_random_uuid(), 'LOGISTICS', '운송장 라이프사이클과 상태머신 설계', 'CONCEPT', 143, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Modular Monolith 구조화 전략', 'CONCEPT', 144, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'Java/Kotlin 동시성 도구 지도 — Executor부터 코루틴까지', 'CONCEPT', 145, false),
  (gen_random_uuid(), 'DATABASE', '복제 지연(Replication Lag) 대응 패턴', 'CONCEPT', 146, false),
  (gen_random_uuid(), 'INFRA', '메트릭 설계 실전 — RED·USE·SLO 대시보드', 'CONCEPT', 147, false),
  (gen_random_uuid(), 'CS', '확률적 자료구조 — Bloom Filter·HyperLogLog', 'CONCEPT', 148, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '클라우드 파일 스토리지 설계 — 청크·동기화·중복 제거', 'DESIGN', 149, false),
  (gen_random_uuid(), 'LOGISTICS', '물류 네트워크 설계 — 허브앤스포크 vs P2P', 'CONCEPT', 150, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'MSA 분리 시점과 Strangler Fig 패턴', 'CONCEPT', 151, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'HikariCP 커넥션 풀 튜닝', 'CONCEPT', 152, false),
  (gen_random_uuid(), 'DATABASE', '무중단 스키마 변경 — Online DDL·gh-ost', 'CONCEPT', 153, false),
  (gen_random_uuid(), 'INFRA', '로그 파이프라인 — Loki·ELK 비교', 'CONCEPT', 154, false),
  (gen_random_uuid(), 'CS', 'DNS와 서비스 디스커버리', 'CONCEPT', 155, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '근접 검색 — Geohash vs QuadTree vs S2', 'CONCEPT', 156, false),
  (gen_random_uuid(), 'LOGISTICS', '반품(역물류) 프로세스와 시스템 설계', 'CONCEPT', 157, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'API Gateway와 BFF 패턴', 'CONCEPT', 158, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'Spring Cache + Redis 실전 — TTL·무효화', 'CONCEPT', 159, false),
  (gen_random_uuid(), 'DATABASE', '슬로우 쿼리 진단 루틴', 'CONCEPT', 160, false),
  (gen_random_uuid(), 'INFRA', 'AWS 오토스케일링과 용량 계획', 'CONCEPT', 161, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Uber 배차 매칭 시스템 설계', 'DESIGN', 162, false),
  (gen_random_uuid(), 'LOGISTICS', '멀티채널 재고 정합성 — 오픈마켓 연동', 'CONCEPT', 163, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '서비스 간 통신 — 동기 vs 비동기 선택 기준', 'CONCEPT', 164, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'Testcontainers 통합 테스트 전략', 'CONCEPT', 165, false),
  (gen_random_uuid(), 'DATABASE', 'Redis 자료구조 활용 — 랭킹·큐·카운터', 'CONCEPT', 166, false),
  (gen_random_uuid(), 'INFRA', '장애 대응 프로세스 — 온콜·포스트모템', 'CONCEPT', 167, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '티켓 예매 시스템 — 대기열·좌석 락·부정 방지', 'DESIGN', 168, false),
  (gen_random_uuid(), 'LOGISTICS', '풀필먼트 자동화 — AGV·GTP·소터', 'CONCEPT', 169, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '분산 추적과 컨텍스트 전파', 'CONCEPT', 170, false),
  (gen_random_uuid(), 'BACKEND_DEV', '예외 설계와 에러 응답 표준화 (RFC 7807)', 'CONCEPT', 171, false),
  (gen_random_uuid(), 'DATABASE', 'Redis 캐시 무효화와 Stampede 방지', 'CONCEPT', 172, false),
  (gen_random_uuid(), 'INFRA', '클라우드 비용 최적화 — FinOps 기초', 'CONCEPT', 173, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '광고 클릭 집계 시스템 — 스트림 집계·지연 데이터', 'DESIGN', 174, false),
  (gen_random_uuid(), 'LOGISTICS', 'OMS-WMS-TMS 인터페이스 — 이벤트 계약 설계', 'CONCEPT', 175, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '이벤트 스키마 진화 — Avro·Schema Registry·호환성', 'CONCEPT', 176, false),
  (gen_random_uuid(), 'BACKEND_DEV', '페이지네이션 구현 — Offset vs Cursor(keyset)', 'CONCEPT', 177, false),
  (gen_random_uuid(), 'DATABASE', 'B+Tree vs LSM Tree — RocksDB 관점', 'CONCEPT', 178, false),
  (gen_random_uuid(), 'INFRA', '시크릿 관리 — Vault·Secrets Manager', 'CONCEPT', 179, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '실시간 게임 리더보드 — Sorted Set·샤딩', 'DESIGN', 180, false),
  (gen_random_uuid(), 'LOGISTICS', '배송비·운임 계산 엔진 설계', 'CONCEPT', 181, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'DLQ와 재처리 설계', 'CONCEPT', 182, false),
  (gen_random_uuid(), 'BACKEND_DEV', '파일 업로드 설계 — Presigned URL', 'CONCEPT', 183, false),
  (gen_random_uuid(), 'DATABASE', 'DynamoDB Single Table Design', 'CONCEPT', 184, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 메시지 큐 내부 — Kafka 파티션·오프셋·ISR', 'CONCEPT', 185, false),
  (gen_random_uuid(), 'LOGISTICS', '쿠팡 로켓배송 아키텍처 분석', 'CONCEPT', 186, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Saga 보상 트랜잭션 실패 처리 심화', 'CONCEPT', 187, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'Spring Batch 기초 — 청크·재시작', 'CONCEPT', 188, false),
  (gen_random_uuid(), 'DATABASE', '시계열 데이터 저장 전략', 'CONCEPT', 189, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '캐시 장애 3종 — Stampede·Penetration·Avalanche', 'CONCEPT', 190, false),
  (gen_random_uuid(), 'LOGISTICS', '컬리 샛별배송 — 시간제약 물류 설계', 'CONCEPT', 191, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'API 버저닝과 하위호환 마이그레이션', 'CONCEPT', 192, false),
  (gen_random_uuid(), 'BACKEND_DEV', '웹훅 수신 처리 — 서명 검증·재시도 방어', 'CONCEPT', 193, false),
  (gen_random_uuid(), 'DATABASE', '백업·복구와 PITR', 'CONCEPT', 194, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'CDC 파이프라인 — Debezium·스냅샷·순서 보장', 'CONCEPT', 195, false),
  (gen_random_uuid(), 'LOGISTICS', '아마존 FBA와 3PL 모델 비교', 'CONCEPT', 196, false),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '멀티테넌시 아키텍처 — 격리 수준 비교', 'CONCEPT', 197, false),
  (gen_random_uuid(), 'BACKEND_DEV', 'API 성능 측정과 프로파일링 루틴', 'CONCEPT', 198, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 트랜잭션 총정리 — 2PC vs Saga vs TCC', 'CONCEPT', 199, false),
  (gen_random_uuid(), 'LOGISTICS', 'ETA 예측 시스템 — 피처·모델·서빙', 'CONCEPT', 200, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'CAP·PACELC 실전 적용 — 시스템별 분류', 'CONCEPT', 201, false),
  (gen_random_uuid(), 'LOGISTICS', '물류 KPI 데이터 모델 — OTD·재고회전율', 'CONCEPT', 202, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '멱등성 있는 결제 시스템 설계', 'DESIGN', 203, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '장애 격리 패턴 — Circuit Breaker·Bulkhead·Backpressure', 'CONCEPT', 204, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '핫 파티션(Hot Partition) 문제와 해결', 'CONCEPT', 205, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '검색 엔진 기초 — 역색인·BM25·랭킹', 'CONCEPT', 206, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '실시간 협업 편집 — OT vs CRDT', 'CONCEPT', 207, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '웹훅 전달 시스템 설계 — 서명·재시도·DLQ', 'DESIGN', 208, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '대용량 처리 아키텍처 — Lambda vs Kappa', 'CONCEPT', 209, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '멀티 리전 아키텍처 — Active-Active·데이터 주권', 'CONCEPT', 210, false),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '모니터링·알림 시스템 설계', 'DESIGN', 211, false);
