-- 1년(52주) 학습 커리큘럼 시드 — 코치 7종이 설계한 364개 주제.
--
-- 주간 로테이션(주 7장): 시스템디자인 2 · 물류 1 · 아키텍처 1 · DB 1 · 백엔드구현 1 · 인프라/CS 격주 1
-- CLAUDE.md 우선순위(시스템디자인 최우선, 물류·백엔드 주력, DB·인프라·CS 보조) 반영.
-- 3페이즈 구성: 1~17주 기반 심화 → 18~35주 프로덕션·스케일 → 36~52주 케이스·면접 마스터리.
--
-- display_order 101~464 = 학습 순서(일 단위). 기존 대기 주제(1~3)가 먼저 소진된다.
-- 생성 파이프라인이 이 순서대로 매일 최대 3장을 생성하므로 시드만으로 1년 이상을 커버한다.

INSERT INTO curriculum_topics (id, area, title, mode, display_order, generated, planned_date)
VALUES
  -- ── 1주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'LSM-Tree vs B+Tree 저장 엔진 — SSTable·Compaction·Write Amplification', 'CONCEPT', 101, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '주문 프로미스 — ATP·CTP·컷오프·배송약속 계산', 'CONCEPT', 102, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Aggregate 설계 규칙 — 불변식·크기 논쟁·트랜잭션 경계', 'CONCEPT', 103, false, NULL),
  (gen_random_uuid(), 'DATABASE', '인덱스 접근 최적화 — Index Merge·Skip Scan·ICP·MRR', 'CONCEPT', 104, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '복제 프로토콜 — 리더 기반·체인 복제·CRAQ', 'CONCEPT', 105, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'JVM 메모리 구조 — Heap·Metaspace·Stack·TLAB·Off-heap', 'CONCEPT', 106, false, NULL),
  (gen_random_uuid(), 'INFRA', 'K8s 네트워킹 심화 — Service·Ingress·CNI·kube-proxy', 'CONCEPT', 107, false, NULL),
  -- ── 2주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 시계 — TrueTime·HLC·Spanner 외부 일관성', 'CONCEPT', 108, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '재고 원장 설계 — 이중기입·트랜잭션 로그·잔액 스냅샷', 'CONCEPT', 109, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Aggregate 참조 전략 — ID 참조·객체 참조·최종 일관성', 'CONCEPT', 110, false, NULL),
  (gen_random_uuid(), 'DATABASE', '인덱스 쓰기 비용 — 쓰기 증폭·페이지 분할·리빌드 전략', 'CONCEPT', 111, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'CDN 내부 심화 — 엣지 캐시 계층·Origin Shield·무효화 전파', 'CONCEPT', 112, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'Garbage Collector 심화 — G1 vs ZGC·STW·Region·Concurrent', 'CONCEPT', 113, false, NULL),
  (gen_random_uuid(), 'CS', '리눅스 I/O 멀티플렉싱 — select·epoll·io_uring 진화', 'CONCEPT', 114, false, NULL),
  -- ── 3주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '트랜잭션 격리수준 심화 — Write Skew·Phantom·SSI 직렬화', 'CONCEPT', 115, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', 'SKU·바코드·시리얼 — GS1·GTIN·Lot·Serial 추적', 'CONCEPT', 116, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Entity와 Value Object — 식별자·불변성·동등성 판단', 'CONCEPT', 117, false, NULL),
  (gen_random_uuid(), 'DATABASE', '클러스터드 인덱스와 PK 설계 — InnoDB·Heap·UUIDv7·페이지 분할', 'CONCEPT', 118, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 시스템의 시간 — Lamport·Vector Clock·인과성', 'CONCEPT', 119, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'GC 로그·힙 덤프 분석 — Allocation Rate·Promotion·OOM 진단', 'CONCEPT', 120, false, NULL),
  (gen_random_uuid(), 'INFRA', 'K8s 스토리지·StatefulSet — PV/PVC·StorageClass·CSI', 'CONCEPT', 121, false, NULL),
  -- ── 4주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 합의 Raft 심화 — 리더 선출·로그 복제·멤버십 변경', 'CONCEPT', 122, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '슬로팅 최적화 — ABC 분석·회전율·피킹 동선 배치', 'CONCEPT', 123, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Rich Domain Model — Anemic 탈출·행위 응집·캡슐화', 'CONCEPT', 124, false, NULL),
  (gen_random_uuid(), 'DATABASE', '인덱스 통계·히스토그램·카디널리티 — 옵티마이저 오판 진단', 'CONCEPT', 125, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Paxos·Multi-Paxos·ZAB — 합의 알고리즘 계보와 트레이드오프', 'CONCEPT', 126, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '스레드풀 사이징 — 리틀의 법칙·CPU/IO Bound·큐·거부 정책', 'CONCEPT', 127, false, NULL),
  (gen_random_uuid(), 'CS', '소켓 내부 — 백로그·TIME_WAIT·SO_REUSEPORT·튜닝', 'CONCEPT', 128, false, NULL),
  -- ── 5주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 트랜잭션 심화 — 2PC 장애 모드·3PC·TCC 보상', 'CONCEPT', 129, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '피킹 전략 — 싱글·멀티·배치·존·웨이브 피킹 비교', 'CONCEPT', 130, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '도메인 이벤트 vs 통합 이벤트 — 경계·버저닝·발행 시점', 'CONCEPT', 131, false, NULL),
  (gen_random_uuid(), 'DATABASE', '파셜 인덱스·함수 기반 인덱스 — 조건부·표현식 인덱싱', 'CONCEPT', 132, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '소셜 그래프 저장 설계 — 인접리스트·샤딩·상호 팔로우', 'DESIGN', 133, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'Java Virtual Threads (Loom) — Carrier·Pinning·구조적 동시성', 'CONCEPT', 134, false, NULL),
  (gen_random_uuid(), 'INFRA', 'K8s 리소스 관리 — requests/limits·QoS·OOMKilled', 'CONCEPT', 135, false, NULL),
  -- ── 6주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 락 비교 설계 — Zookeeper·etcd·Fencing Token·리스', 'DESIGN', 136, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '웨이브·배치 릴리즈 — 오더풀·로드밸런싱·컷오프', 'CONCEPT', 137, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Context Map 관계 — Customer-Supplier·Conformist·OHS', 'CONCEPT', 138, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'PostgreSQL 특화 인덱스 — GIN·GiST·BRIN·Hash 용도별 선택', 'CONCEPT', 139, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '대규모 세션 관리 설계 — 스티키 vs 무상태·토큰·세션 스토어', 'DESIGN', 140, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'Kotlin Coroutines — 구조적 동시성·Dispatcher·Job 계층', 'CONCEPT', 141, false, NULL),
  (gen_random_uuid(), 'CS', '가상 메모리 심화 — 페이지 캐시·mmap·Copy-on-Write·스왑', 'CONCEPT', 142, false, NULL),
  -- ── 7주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Quorum 정합성 — R+W>N·Read Repair·Hinted Handoff·Merkle', 'CONCEPT', 143, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '패킹·카톤화 — 박스 추천·집품 검수·중량 검증', 'CONCEPT', 144, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Anti-corruption Layer — 레거시 격리·번역기·외부 연동', 'CONCEPT', 145, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'JSON·JSONB 컬럼 설계 — 인덱싱·생성 컬럼·스키마리스 함정', 'CONCEPT', 146, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 유니크 ID 설계 — Snowflake·ULID·시계 역행·Clock Skew', 'DESIGN', 147, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '코루틴 취소·예외 전파 — Cancellation·SupervisorJob·타임아웃', 'CONCEPT', 148, false, NULL),
  (gen_random_uuid(), 'INFRA', 'AWS 네트워킹 심화 — Transit Gateway·PrivateLink·하이브리드', 'CONCEPT', 149, false, NULL),
  -- ── 8주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Kafka 내부 심화 — 파티션·리더 선출·ISR·High Watermark', 'CONCEPT', 150, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '크로스도킹 — 입출고 직결·환적·JIT 동기화', 'CONCEPT', 151, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Strangler Fig 패턴 — 점진 이관·라우팅·병행 운영·롤백', 'CONCEPT', 152, false, NULL),
  (gen_random_uuid(), 'DATABASE', '전문검색(FTS) — MySQL FULLTEXT vs PostgreSQL tsvector·GIN', 'CONCEPT', 153, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Kafka 컨슈머 리밸런싱 — Eager vs Cooperative Sticky·정적 멤버십', 'CONCEPT', 154, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'CompletableFuture vs 코루틴 — 조합·예외·블로킹 IO 격리', 'CONCEPT', 155, false, NULL),
  (gen_random_uuid(), 'CS', '컨텍스트 스위칭 비용 — 캐시 오염·시스템콜·vDSO', 'CONCEPT', 156, false, NULL),
  -- ── 9주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Kafka 정확히 한 번 — 멱등 프로듀서·트랜잭션·Read Committed', 'CONCEPT', 157, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '물류센터 운영 면접 — 피킹 정확도·재고 정합·예외 대응', 'INTERVIEW', 158, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Hexagonal Architecture — Port & Adapter·의존성 역전', 'CONCEPT', 159, false, NULL),
  (gen_random_uuid(), 'DATABASE', '조인 알고리즘 — Nested Loop·Hash Join·Merge Join 선택 원리', 'CONCEPT', 160, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Kafka 저장·보존 — Log Segment·Compaction·Tiered Storage', 'CONCEPT', 161, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'Spring AOP·프록시 내부 — Dynamic Proxy·CGLIB·자기호출 함정', 'CONCEPT', 162, false, NULL),
  (gen_random_uuid(), 'INFRA', 'IAM 설계 — 최소권한·Assume Role·Permission Boundary·IRSA', 'CONCEPT', 163, false, NULL),
  -- ── 10주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '메시지 큐 선택 설계 — Kafka vs RabbitMQ vs SQS vs Pulsar', 'DESIGN', 164, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '미들마일 — 간선 운송·거점 네트워크·적재율 최적화', 'CONCEPT', 165, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Clean vs Onion Architecture — 의존성 규칙·계층 비교', 'CONCEPT', 166, false, NULL),
  (gen_random_uuid(), 'DATABASE', '서브쿼리·CTE 최적화 — Semi Join·Materialization·상관 서브쿼리', 'CONCEPT', 167, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Redis Cluster 내부 — Hash Slot·Gossip·리샤딩·MOVED/ASK', 'CONCEPT', 168, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'JPA 영속성 컨텍스트 — 1차 캐시·Dirty Checking·Flush·쓰기지연', 'CONCEPT', 169, false, NULL),
  (gen_random_uuid(), 'CS', 'CPU 캐시와 NUMA — 캐시 라인·False Sharing·메모리 지역성', 'CONCEPT', 170, false, NULL),
  -- ── 11주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '인메모리 캐시 내부 — Memcached vs Redis·슬랩·이벤트 루프', 'CONCEPT', 171, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '허브 소팅 — 자동 분류기·체이트·소터 처리량 설계', 'CONCEPT', 172, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '레이어드 아키텍처의 함정 — 트랜잭션 스크립트·계층 누수', 'CONCEPT', 173, false, NULL),
  (gen_random_uuid(), 'DATABASE', '정렬·집계 최적화 — Filesort·sort_buffer·work_mem 튜닝', 'CONCEPT', 174, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '실시간 전송 선택 — Long Polling·SSE·WebSocket·HTTP/3', 'CONCEPT', 175, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'JPA N+1·페치 전략 — Fetch Join·EntityGraph·Batch Size', 'CONCEPT', 176, false, NULL),
  (gen_random_uuid(), 'INFRA', '이벤트 메시징 선택 — SQS·Kinesis·MSK 순서·보존·처리량', 'CONCEPT', 177, false, NULL),
  -- ── 12주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '캐시 일관성 설계 — Write-Through·Write-Back·무효화·이중 쓰기', 'DESIGN', 178, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '운임 계산 — 요율표·Chargeable Weight·할증·부피중량', 'CONCEPT', 179, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Spring Modulith — 모듈 경계 검증·이벤트·아키텍처 테스트', 'CONCEPT', 180, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'InnoDB 버퍼풀·체인지 버퍼 — 페이지 캐시·LRU·플러시', 'CONCEPT', 181, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 캐시 설계 — 핫키·복제·샤딩 라우팅·Client-Side 캐시', 'DESIGN', 182, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'HikariCP 커넥션 풀 튜닝 — Pool Size·타임아웃·Leak Detection', 'CONCEPT', 183, false, NULL),
  (gen_random_uuid(), 'CS', '파일시스템과 fsync — 저널링·더티 페이지·내구성 보장', 'CONCEPT', 184, false, NULL),
  -- ── 13주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Bloom Filter 심화 — 오탐률·Counting·Cuckoo·삭제 지원', 'CONCEPT', 185, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '관세·통관 — CBE·HS 코드·수입신고·개인통관부호', 'CONCEPT', 186, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '패키지 구조 전략 — 계층형 vs 기능형·모듈 응집도', 'CONCEPT', 187, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'PostgreSQL VACUUM·Bloat — Autovacuum·Freeze·Wraparound', 'CONCEPT', 188, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'HyperLogLog·Count-Min Sketch — 카디널리티·빈도 추정 근사', 'CONCEPT', 189, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'Jackson 직렬화 함정 — 역직렬화·다형성·Null·순환참조·성능', 'CONCEPT', 190, false, NULL),
  (gen_random_uuid(), 'INFRA', 'RDS/Aurora 운영 — Multi-AZ 페일오버·Read Replica·PITR', 'CONCEPT', 191, false, NULL),
  -- ── 14주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '역색인 검색 엔진 내부 — Lucene·Segment·Posting List·NRT', 'CONCEPT', 192, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '콜드체인 — 온도대·이탈 감지·HACCP·CA 저장', 'CONCEPT', 193, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'API 버저닝과 하위호환 — URI·헤더·Deprecation 정책', 'CONCEPT', 194, false, NULL),
  (gen_random_uuid(), 'DATABASE', '락 심화 — Insert Intention·외래키·메타데이터 락', 'CONCEPT', 195, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '시계열 저장 심화 — TSDB·Gorilla 압축·다운샘플링·롤업·보존', 'CONCEPT', 196, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '시간·타임존·돈 계산 — Instant·UTC 저장·BigDecimal·반올림', 'CONCEPT', 197, false, NULL),
  (gen_random_uuid(), 'CS', 'HTTP/2·HTTP/3 내부 — 멀티플렉싱·HOL 블로킹·QUIC·0-RTT', 'CONCEPT', 198, false, NULL),
  -- ── 15주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'gRPC 심화 — HTTP/2·Protobuf·스트리밍·Deadline·Interceptor', 'CONCEPT', 199, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '위험물 — UN 번호·DG 클래스·분리 적재·MSDS', 'CONCEPT', 200, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'BFF (Backend for Frontend) — 클라이언트별 조합·소유권', 'CONCEPT', 201, false, NULL),
  (gen_random_uuid(), 'DATABASE', '데드락 분석 — 로그 판독·대기 그래프·순환 방지 설계', 'CONCEPT', 202, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '서비스 디스커버리 설계 — Client vs Server-Side·Consul·헬스체크', 'DESIGN', 203, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '예외 설계 — Checked/Unchecked·sealed·Result·에러 변환', 'CONCEPT', 204, false, NULL),
  (gen_random_uuid(), 'INFRA', '컨테이너 이미지 최적화 — 멀티스테이지·distroless·레이어 캐시', 'CONCEPT', 205, false, NULL),
  -- ── 16주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'eBPF 데이터패스 — Cilium·사이드카리스 메시·커널 관측', 'CONCEPT', 206, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '라우팅 알고리즘 기초 — TSP·VRP·CVRP·VRPTW·Savings', 'CONCEPT', 207, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'API Gateway vs Service Mesh — 트래픽·횡단관심사·경계', 'CONCEPT', 208, false, NULL),
  (gen_random_uuid(), 'DATABASE', '인덱스 안티패턴 체크리스트 — 중복·미사용·저선택도·순서 오류', 'REVIEW', 209, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '로드밸런싱 알고리즘 심화 — Least Conn·P2C·Consistent Hash·EWMA', 'CONCEPT', 210, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '널 안전·경계값·불변식 코드 리뷰 — Optional·Off-by-one·방어적 복사', 'REVIEW', 211, false, NULL),
  (gen_random_uuid(), 'CS', 'TLS 심화 — 1.3 핸드셰이크·세션 재개·mTLS·인증서 체인', 'CONCEPT', 212, false, NULL),
  -- ── 17주차 (기반 심화) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '객체 스토리지 내부 — S3 일관성·멀티파트·Erasure Coding', 'CONCEPT', 213, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '주문·재고 정합성 면접 — 프로미스·원장·크로스도킹', 'INTERVIEW', 214, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '아키텍처 경계 설계 면접 — 의존성 방향·계층 위반 압박', 'INTERVIEW', 215, false, NULL),
  (gen_random_uuid(), 'DATABASE', '슬로우 쿼리 처방 면접 — EXPLAIN 즉석 진단·인덱스·조인 튜닝', 'INTERVIEW', 216, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '저장·인덱스 설계 면접 — LSM 선택 근거·읽기 증폭 방어 압박', 'INTERVIEW', 217, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'JVM 장애 대응 압박 면접 — GC·OOM·스레드 덤프 진단', 'INTERVIEW', 218, false, NULL),
  (gen_random_uuid(), 'INFRA', 'K8s 트러블슈팅 면접 — CrashLoop·OOM·네트워크 단절 근인 추적', 'INTERVIEW', 219, false, NULL),
  -- ── 18주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '메시징 설계 면접 — 정확히 한 번의 허상·멱등 컨슈머 압박', 'INTERVIEW', 220, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '재고 이벤트 소싱 — Event Sourcing·CQRS·원장 재구성', 'CONCEPT', 221, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Saga 오케스트레이터 상태머신 — 상태 영속화·타임아웃·재개', 'CONCEPT', 222, false, NULL),
  (gen_random_uuid(), 'DATABASE', '온라인 DDL과 무중단 스키마 변경 — gh-ost·pt-osc·PostgreSQL DDL 락', 'CONCEPT', 223, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '핫스팟·셀럽 문제 — Fan-out 폭증·키 복제·요청 병합·부하 분산', 'CONCEPT', 224, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'Spring Batch 대용량 처리 — Chunk·Restart·Skip·병렬 스텝', 'CONCEPT', 225, false, NULL),
  (gen_random_uuid(), 'CS', 'OS·네트워크 내부 면접 — epoll·TIME_WAIT·페이지 캐시 압박', 'INTERVIEW', 226, false, NULL),
  -- ── 19주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Back-pressure 심화 — Reactive Streams·크레딧·큐·Little 법칙', 'CONCEPT', 227, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '물류 이벤트 표준 — EDI·EPCIS·API 스키마·메시지 계약', 'CONCEPT', 228, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Process Manager — 상태 저장 라우터·장기 프로세스·상관관계', 'CONCEPT', 229, false, NULL),
  (gen_random_uuid(), 'DATABASE', '대용량 테이블 마이그레이션 — 배치 백필·듀얼 라이트·컷오버', 'CONCEPT', 230, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Load Shedding·우아한 성능저하 — 우선순위·적응형·부분 응답', 'CONCEPT', 231, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '커서·키셋 페이지네이션 구현 — No Offset·정렬 키·중복·성능', 'CONCEPT', 232, false, NULL),
  (gen_random_uuid(), 'INFRA', '오토스케일링 전략 비교 — HPA·KEDA·Karpenter·Cluster Autoscaler', 'CONCEPT', 233, false, NULL),
  -- ── 20주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'A/B 실험 플랫폼 설계 — 배정 해싱·노출 로그·지표 집계', 'DESIGN', 234, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '지오코딩·주소 정제 — 정규화·매칭·행정동·PNU 좌표', 'CONCEPT', 235, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '멱등 컨슈머 패턴 — 메시지 중복·처리 키·상태 기반 방어', 'CONCEPT', 236, false, NULL),
  (gen_random_uuid(), 'DATABASE', '백업·복구와 PITR — 논리/물리 백업·바이너리 로그·WAL 아카이빙', 'CONCEPT', 237, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'API 배칭·DataLoader — N+1 RPC 제거·부분 실패 처리', 'DESIGN', 238, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'QueryDSL 동적 쿼리 — BooleanBuilder·동적 정렬·프로젝션·N+1', 'CONCEPT', 239, false, NULL),
  (gen_random_uuid(), 'CS', 'DNS 내부 — 재귀 질의·캐싱 TTL·네거티브 캐시·DoH', 'CONCEPT', 240, false, NULL),
  -- ── 21주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '다계층 캐시 무효화 — CDN·앱·DB·버전 태그·Purge 전파', 'CONCEPT', 241, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '스캔 이벤트 보정 설계 — 누락·역순·중복 스캔 처리', 'DESIGN', 242, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Inbox 패턴 — 소비자 중복 제거·수신 저장·정확 처리', 'CONCEPT', 243, false, NULL),
  (gen_random_uuid(), 'DATABASE', '복제 지연 대응 — Read-Your-Writes·읽기 라우팅·Semi-Sync', 'CONCEPT', 244, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '스트림 처리 심화 — Flink·상태 저장·Checkpoint·Exactly-Once', 'CONCEPT', 245, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'JPA 벌크 연산 — Bulk Update/Delete·배치 Insert·영속성 컨텍스트', 'CONCEPT', 246, false, NULL),
  (gen_random_uuid(), 'INFRA', '시크릿·구성 관리 — Secrets Manager·Vault·External Secrets', 'CONCEPT', 247, false, NULL),
  -- ── 22주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '윈도잉·Watermark — Tumbling·Sliding·Session·지연 데이터', 'CONCEPT', 248, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '리드타임·SLA 관리 — 구간 리드타임·프로미스 데이트·OTD', 'CONCEPT', 249, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '재시도와 DLQ 설계 — 지수 백오프·독약 메시지·재처리', 'CONCEPT', 250, false, NULL),
  (gen_random_uuid(), 'DATABASE', '자동 페일오버·HA — Orchestrator·Patroni·Split-Brain 방지', 'CONCEPT', 251, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Lambda vs Kappa 아키텍처 — 배치·스트림 통합·재처리', 'CONCEPT', 252, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '트랜잭션 이벤트 리스너 — AFTER_COMMIT·발행 시점·Outbox 대안', 'CONCEPT', 253, false, NULL),
  (gen_random_uuid(), 'CS', '해시테이블 내부 — 충돌·오픈 어드레싱·리사이징·SipHash', 'CONCEPT', 254, false, NULL),
  -- ── 23주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '불변 로그와 삭제 — Append-Only·GDPR·Crypto-shredding', 'CONCEPT', 255, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '수요 예측 — 시계열·계절성·안전재고·서비스 레벨', 'CONCEPT', 256, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '멱등 이벤트 컨슈머 파이프라인 — Inbox·DLQ·재처리 설계', 'DESIGN', 257, false, NULL),
  (gen_random_uuid(), 'DATABASE', '커넥션 풀·프록시 — ProxySQL·PgBouncer·풀링 모드·한계', 'CONCEPT', 258, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'CQRS 설계 — 읽기/쓰기 분리·Materialized View·정합성 지연', 'DESIGN', 259, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '@Async 비동기 처리 — Executor·예외·트랜잭션 경계·데코레이터', 'CONCEPT', 260, false, NULL),
  (gen_random_uuid(), 'INFRA', '클라우드 보안 — WAF·Shield·DDoS 방어·K8s Network Policy', 'CONCEPT', 261, false, NULL),
  -- ── 24주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '실시간 지표 집계 설계 — 윈도우 집계·정확히 한 번·상태 백엔드', 'DESIGN', 262, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '재고 보충 — ROP·EOQ·(s,S) 정책·자동 발주', 'CONCEPT', 263, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '이벤트 스키마 레지스트리 — Avro·호환성 규칙·계약 진화', 'CONCEPT', 264, false, NULL),
  (gen_random_uuid(), 'DATABASE', '쿼리 안티패턴 체크리스트 — 함수 래핑·암묵 형변환·IN 폭발·SELECT *', 'REVIEW', 265, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'OLTP vs OLAP·HTAP — 컬럼 저장·벡터화·데이터 웨어하우스', 'CONCEPT', 266, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '웹훅 수신 멱등 처리 — 서명 검증·중복 제거·재처리·순서', 'CONCEPT', 267, false, NULL),
  (gen_random_uuid(), 'CS', '정렬 자료구조 — Skip List·B-Tree·Red-Black 비교', 'CONCEPT', 268, false, NULL),
  -- ── 25주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '데이터 레이크하우스 — Iceberg·Delta·파티셔닝·Time Travel', 'CONCEPT', 269, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '캐리어 게이트웨이 — 택배사 연동·운송장 발번·webhook', 'DESIGN', 270, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '분산 락 vs 큐 직렬화 — 순서 보장·단일 소비자·경합 회피', 'CONCEPT', 271, false, NULL),
  (gen_random_uuid(), 'DATABASE', '무중단 마이그레이션 설계 — 20억 행 운송장 테이블 컷오버', 'DESIGN', 272, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '관측성 3축 심화 — Metric·Log·Trace·카디널리티 폭발', 'CONCEPT', 273, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '분산 락 구현 Redisson — RLock·Watchdog·Lease·Fencing Token', 'CONCEPT', 274, false, NULL),
  (gen_random_uuid(), 'INFRA', 'DNS·글로벌 트래픽 관리 — Route 53·GSLB·Failover·Latency 라우팅', 'CONCEPT', 275, false, NULL),
  -- ── 26주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 추적 설계 — OpenTelemetry·Context 전파·Sampling', 'DESIGN', 276, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '이벤트 파이프라인 면접 — 멱등·순서·정합성 보장', 'INTERVIEW', 277, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '메시지 유실·중복 장애 면접 — 정합성 복구 시나리오 압박', 'INTERVIEW', 278, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'Redis 자료구조 설계 — Sorted Set·Hash·Bitmap·HyperLogLog', 'CONCEPT', 279, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '장애 감지 — 헬스체크·하트비트·Phi Accrual·멤버십', 'CONCEPT', 280, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'Rate Limiting 구현 — Token Bucket·Bucket4j·Redis·분산 제한', 'CONCEPT', 281, false, NULL),
  (gen_random_uuid(), 'CS', '캐시 교체 알고리즘 구현 — LRU·LFU·TinyLFU·Clock', 'CONCEPT', 282, false, NULL),
  -- ── 27주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Circuit Breaker 심화 — 상태 전이·Half-Open·타임아웃·격리', 'CONCEPT', 283, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '배송비 엔진 — 요율·구간·무료배송 임계·정책 룰', 'CONCEPT', 284, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Read Model 재구축 — 리플레이·백필·무중단 전환·검증', 'CONCEPT', 285, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'Redis 영속성·HA — RDB·AOF·fsync·Sentinel 페일오버', 'CONCEPT', 286, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Bulkhead·격벽 설계 — 스레드풀 격리·연결 풀·자원 분리', 'DESIGN', 287, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '분산 스케줄링 — ShedLock·다중 인스턴스 중복 실행 방지·Cron', 'CONCEPT', 288, false, NULL),
  (gen_random_uuid(), 'INFRA', '서비스 메시 도입 판단 — Istio·mTLS·사이드카 비용·트래픽 제어', 'CONCEPT', 289, false, NULL),
  -- ── 28주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Cell 기반 아키텍처 — 셀 분할·Blast Radius·Shuffle Sharding', 'CONCEPT', 290, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '출고 우선순위 — 프로모션·SLA·용량 제약 스케줄링', 'CONCEPT', 291, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '이벤트 스냅샷 전략 — 스냅샷 주기·리플레이 비용·버전 관리', 'CONCEPT', 292, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'MongoDB 스키마 설계 — Embedding vs Referencing·문서 크기', 'CONCEPT', 293, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '선형성 검증 — Jepsen·장애 주입·일관성 테스트', 'CONCEPT', 294, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '외부 HTTP 클라이언트 설계 — 타임아웃·재시도·커넥션풀·폴백', 'DESIGN', 295, false, NULL),
  (gen_random_uuid(), 'CS', '문자 인코딩·문자열 — UTF-8·정규화·Grapheme·콜레이션', 'CONCEPT', 296, false, NULL),
  -- ── 29주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'Retry 폭풍 방어 — 지수 백오프·Jitter·서킷·Retry Budget', 'CONCEPT', 297, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '물류 KPI 설계 — OTD·Fill Rate·재고회전·대시보드', 'CONCEPT', 298, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '데이터 소유권과 조회 조인 — SSOT·데이터 복제·API 조합', 'CONCEPT', 299, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'DynamoDB 싱글 테이블 설계 — PK·SK·GSI·키 오버로딩', 'CONCEPT', 300, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '지리공간 인덱스 심화 — Geohash·S2·H3·R-Tree·근접 검색', 'CONCEPT', 301, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '파일 업로드·다운로드 스트리밍 설계 — Multipart·Presigned·메모리', 'DESIGN', 302, false, NULL),
  (gen_random_uuid(), 'INFRA', '클라우드 비용 최적화 — FinOps·Spot·Savings Plan·전송비 절감', 'CONCEPT', 303, false, NULL),
  -- ── 30주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '실시간 위치 추적 설계 — GPS 수집·QuadTree·핫셀·업데이트 폭증', 'DESIGN', 304, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '풀필먼트 네트워크 설계 — FC 입지·재고 배치·커버리지', 'CONCEPT', 305, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'GraphQL Federation — 서브그래프·스키마 합성·소유권 경계', 'CONCEPT', 306, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'Cassandra 파티션 설계 — Wide Row·핫 파티션·Tombstone', 'CONCEPT', 307, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '근접 서비스 설계 — Nearby·반경 검색·인덱스 갱신·랭킹', 'DESIGN', 308, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '2단 캐시 구현 설계 — Caffeine 로컬+Redis·pub/sub 무효화', 'DESIGN', 309, false, NULL),
  (gen_random_uuid(), 'CS', '압축 알고리즘 — LZ4·Zstd·Snappy·엔트로피 코딩 선택', 'CONCEPT', 310, false, NULL),
  -- ── 31주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '샤딩 전략 심화 — Range·Hash·Geo·Directory·리샤딩', 'CONCEPT', 311, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', 'D2C vs 마켓플레이스 물류 — 풀필먼트·정산·SLA 차이', 'CONCEPT', 312, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '플러그인 아키텍처 — 확장점·SPI·모듈 격리 로딩', 'CONCEPT', 313, false, NULL),
  (gen_random_uuid(), 'DATABASE', '시계열 데이터베이스 — TimescaleDB·하이퍼테이블·롤업·압축', 'CONCEPT', 314, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '이미지 서빙 파이프라인 설계 — 리사이즈·서명 URL·CDN', 'DESIGN', 315, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '동시성 버그 재현 테스트 — CountDownLatch·Awaitility·jcstress', 'CONCEPT', 316, false, NULL),
  (gen_random_uuid(), 'INFRA', '재해복구(DR) 전략 — RTO/RPO·Pilot Light·Warm Standby', 'CONCEPT', 317, false, NULL),
  -- ── 32주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '폴리글랏 정합성 — DB·캐시·검색 인덱스 동기화 지연', 'CONCEPT', 318, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '퀵커머스·MFC — 마이크로 풀필먼트·30분 배송·재고', 'CONCEPT', 319, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Feature Flag 아키텍처 — 릴리스 분리·킬스위치·구성 전파', 'CONCEPT', 320, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'OLAP·컬럼 스토어 — ClickHouse·컬럼 지향·압축·벡터화 실행', 'CONCEPT', 321, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '핫 파티션 완화 설계 — 키 솔팅·Split·Adaptive·부하 재분배', 'DESIGN', 322, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '성능 테스트·프로파일링 — k6/Gatling·async-profiler·Flame Graph', 'CONCEPT', 323, false, NULL),
  (gen_random_uuid(), 'CS', '그래프 탐색 실전 — BFS/DFS 응용·위상정렬·SCC·유니온파인드', 'CONCEPT', 324, false, NULL),
  -- ── 33주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '멀티테넌시 설계 — 격리 모델·Noisy Neighbor·Pool vs Silo', 'DESIGN', 325, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '새벽배송 컷오프 — 주문 마감·피킹 웨이브·배차 동기화', 'CONCEPT', 326, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '서비스 간 인증 — mTLS·토큰 전파·JWT·서비스 아이덴티티', 'CONCEPT', 327, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'CDC 파이프라인 운영 — Debezium 스냅샷·스키마 변경·재처리', 'CONCEPT', 328, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '멱등성 대규모 설계 — Idempotency Key·중복 제거·TTL·저장소', 'DESIGN', 329, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'JPA 성능 코드 리뷰 — N+1·OSIV·벌크·페이징 카운트·플러시', 'REVIEW', 330, false, NULL),
  (gen_random_uuid(), 'INFRA', '부하 테스트·용량 계획 — k6·트래픽 스파이크·Back-pressure', 'CONCEPT', 331, false, NULL),
  -- ── 34주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '순서 보장 소비 — 파티션 순서·키 기반 직렬화·재정렬', 'CONCEPT', 332, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '옴니채널 재고 — BOPIS·Ship-from-Store·통합 가시성', 'CONCEPT', 333, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '모듈 경계와 팀 토폴로지 — Conway 법칙·Stream팀·인지 부하', 'CONCEPT', 334, false, NULL),
  (gen_random_uuid(), 'DATABASE', 'NoSQL 선택 면접 — 접근 패턴 기반 스토어 결정 방어', 'INTERVIEW', 335, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '광고 클릭 집계 면접 — 정확히 한 번·중복·핫키·근사 집계', 'INTERVIEW', 336, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '외부 API 연동 코드 리뷰 — 타임아웃·트랜잭션 내 호출·재시도 폭주', 'REVIEW', 337, false, NULL),
  (gen_random_uuid(), 'CS', '타이머 구현 — Timing Wheel·힙 타이머·틱 정확도', 'CONCEPT', 338, false, NULL),
  -- ── 35주차 (프로덕션·스케일) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '실시간 위치 추적 면접 — 쓰기 폭증·지오인덱스·Fan-out 압박', 'INTERVIEW', 339, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '수요·네트워크 면접 — 예측·보충·풀필먼트 배치', 'INTERVIEW', 340, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '서비스 경계·데이터 소유권 면접 — 분리 기준·조인 압박', 'INTERVIEW', 341, false, NULL),
  (gen_random_uuid(), 'DATABASE', '샤드 키 선택 면접 — 카디널리티·핫스팟·리밸런싱 방어', 'INTERVIEW', 342, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '스트림 파이프라인 면접 — 백프레셔·재처리·순서·정합성 압박', 'INTERVIEW', 343, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'API 성능 저하 진단 면접 — 캐시·커넥션풀·N+1·병목 압박', 'INTERVIEW', 344, false, NULL),
  (gen_random_uuid(), 'INFRA', '운영 트레이드오프 면접 — 스케일·비용·DR·보안 의사결정 압박', 'INTERVIEW', 345, false, NULL),
  -- ── 36주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 키-값 저장소 설계 — DynamoDB 스타일·Quorum·Gossip·Merkle', 'DESIGN', 346, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '물류 도메인 모델링 — Bounded Context·Aggregate·이벤트스토밍', 'CONCEPT', 347, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', 'Durable Execution — Temporal·워크플로 코드화·Saga 진화', 'CONCEPT', 348, false, NULL),
  (gen_random_uuid(), 'DATABASE', '쓰기 집중 테이블 설계 — 대량 INSERT·COPY·인덱스 전략', 'CONCEPT', 349, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 KV 저장소 면접 — 일관성·파티션·핫스팟 트레이드오프 압박', 'INTERVIEW', 350, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '재고 예약·차감 시스템 설계 — 오버셀 방지·예약 TTL·확정/취소', 'DESIGN', 351, false, NULL),
  (gen_random_uuid(), 'CS', '자료구조·알고리즘 내부 면접 — 해시·캐시·그래프 압박', 'INTERVIEW', 352, false, NULL),
  -- ── 37주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 원장 정합성 — 복식부기·멱등·정산·감사·Exactly-Once', 'CONCEPT', 353, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '주문 변경·취소 흐름 — 부분취소·출고중 취소·환불 보상', 'CONCEPT', 354, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '주문 오케스트레이션 서비스 — 상태 저장·타임아웃·보상·재개 설계', 'DESIGN', 355, false, NULL),
  (gen_random_uuid(), 'DATABASE', '운송장 상태 이력 모델링 — 상태 전이·이력 테이블·현재 상태 뷰', 'CONCEPT', 356, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '결제 시스템 설계 — 원장·정합성·멱등·정산·외부 PG 연동', 'DESIGN', 357, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '주문 상태 전이 시스템 설계 — 상태 머신·이벤트·보상·감사 추적', 'DESIGN', 358, false, NULL),
  (gen_random_uuid(), 'INFRA', '커머스 주문 폭증 대응 설계 — 세일 스파이크·대기열·부하 평탄화', 'DESIGN', 359, false, NULL),
  -- ── 38주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '결제 시스템 면접 — 정합성·이중 결제·정산 불일치 압박', 'INTERVIEW', 360, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '쿠팡 로켓배송 설계 — 새벽 풀필먼트+라스트마일 통합', 'DESIGN', 361, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '재고 서비스 분리 — 소유권·예약·정합성·이벤트 발행 설계', 'DESIGN', 362, false, NULL),
  (gen_random_uuid(), 'DATABASE', '정산 원장 모델링 — 복식부기·불변성·멱등 정산·감사 추적', 'CONCEPT', 363, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '조건부 요청·동시성 제어 — ETag·If-Match·버전 충돌', 'CONCEPT', 364, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '배송 추적 시스템 설계 — 폴링→웹훅 전환·이벤트 정규화·재처리', 'DESIGN', 365, false, NULL),
  (gen_random_uuid(), 'CS', '락프리 자료구조 — CAS·ABA·Ring Buffer·Disruptor', 'CONCEPT', 366, false, NULL),
  -- ── 39주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '가상 대기열 시스템 — Virtual Waiting Room·토큰·공정성·폭주', 'CONCEPT', 367, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '배민 실시간 배차 설계 — 음식배달 매칭·묶음·ETA', 'DESIGN', 368, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '재고 정합성 붕괴 면접 — 오버셀·보상·복구 압박', 'INTERVIEW', 369, false, NULL),
  (gen_random_uuid(), 'DATABASE', '트래킹 이벤트 대용량 저장 — 파티셔닝·TTL·콜드 스토리지 계층', 'CONCEPT', 370, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '티켓 예매 시스템 설계 — 좌석 락·오버셀 방지·대기열·재고', 'DESIGN', 371, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '운송장 채번 구현 — 분산 시퀀스·중복 방지·체크 디지트·성능', 'CONCEPT', 372, false, NULL),
  (gen_random_uuid(), 'INFRA', '카오스 엔지니어링 — 가설·장애 주입·게임데이·복원력 검증', 'CONCEPT', 373, false, NULL),
  -- ── 40주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '티켓 예매 면접 — 동시 접속 폭주·오버셀·대기열 공정성 압박', 'INTERVIEW', 374, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '통합 풀필먼트 면접 — 재고·피킹·라스트마일 연결', 'INTERVIEW', 375, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '정합성 Reconciliation — 드리프트 감지·보정 배치·감사', 'CONCEPT', 376, false, NULL),
  (gen_random_uuid(), 'DATABASE', '계층·경로 데이터 모델링 — 인접목록·Closure Table·PostgreSQL ltree', 'CONCEPT', 377, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '호텔·숙박 예약 설계 — 가용성 계산·오버부킹·동시성·검색', 'DESIGN', 378, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '정산 배치 구현 — 대사·멱등·부분 실패 재처리·마감 잠금', 'CONCEPT', 379, false, NULL),
  (gen_random_uuid(), 'CS', '난수·해시 함수 — 균등성·시드·xxHash·암호학적 구분', 'CONCEPT', 380, false, NULL),
  -- ── 41주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '재고 플래시세일 설계 — 오버셀 방지·대기열·핫키·재고 차감', 'DESIGN', 381, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '컬리 새벽배송 설계 — 콜드체인 풀필먼트·컷오프·라우팅', 'DESIGN', 382, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '정산 파이프라인 — 이벤트 집계·멱등·재처리·마감 설계', 'DESIGN', 383, false, NULL),
  (gen_random_uuid(), 'DATABASE', '이력·시점 조회 모델링 — Soft Delete·Temporal Table·SCD Type 2', 'CONCEPT', 384, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '재고 플래시세일 면접 — 핫키·오버셀·재고 정합성 압박', 'INTERVIEW', 385, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '대량 상품 업서트 구현 — Upsert·배치·충돌 병합·부분 성공 응답', 'CONCEPT', 386, false, NULL),
  (gen_random_uuid(), 'INFRA', '물류센터 엣지 인프라 설계 — 엣지 컴퓨팅·오프라인 내구성·동기화', 'DESIGN', 387, false, NULL),
  -- ── 42주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '배차 매칭 알고리즘 — 이분 매칭·수급 균형·배치·탐욕', 'CONCEPT', 388, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', 'Amazon FBA 설계 — 셀러 멀티노드 재고·정산·수수료', 'DESIGN', 389, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '알림 팬아웃 아키텍처 — 채널 추상화·팬아웃·재시도 설계', 'DESIGN', 390, false, NULL),
  (gen_random_uuid(), 'DATABASE', '멀티테넌트 데이터 격리 — 공유/스키마/DB·PostgreSQL RLS', 'CONCEPT', 391, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '경로 엔진 내부 — 도로 그래프·Contraction Hierarchies·A*', 'CONCEPT', 392, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '배송비 계산 구현 — BigDecimal·반올림 정책·구간 요율·통화', 'CONCEPT', 393, false, NULL),
  (gen_random_uuid(), 'CS', '빈 패킹·스케줄링 이론 — First Fit·작업 스케줄링·근사비', 'CONCEPT', 394, false, NULL),
  -- ── 43주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'ETA 예측 시스템 — 실시간 교통·피처·경로·정확도', 'CONCEPT', 395, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '재고 실사·Cycle Count — 순환 실사·차이 조정·원인 분류', 'CONCEPT', 396, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '대량 팬아웃 폭주 면접 — 백프레셔·우선순위·격리 압박', 'INTERVIEW', 397, false, NULL),
  (gen_random_uuid(), 'DATABASE', '데이터 모델링 안티패턴 체크리스트 — EAV·과잉 정규화·Nullable 남용', 'REVIEW', 398, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '라이드 헤일링 설계 — 배차 매칭·수급·ETA·상태 머신', 'DESIGN', 399, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '라이더 배차 배정 구현 — 동시 수락 충돌·타임아웃 재배정·멱등', 'CONCEPT', 400, false, NULL),
  (gen_random_uuid(), 'INFRA', '로드밸런서 운영 — ALB vs NLB·Cross-zone·드레이닝·타임아웃', 'CONCEPT', 401, false, NULL),
  -- ── 44주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '라이드 헤일링 면접 — 배차 경합·수급 불균형·지도 확장 압박', 'INTERVIEW', 402, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '재고 아키텍처 면접 — Saga·이벤트소싱·정합성', 'INTERVIEW', 403, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '서비스 분리 데이터 마이그레이션 — 이중 쓰기·백필·컷오버', 'CONCEPT', 404, false, NULL),
  (gen_random_uuid(), 'DATABASE', '주문·배송 도메인 스키마 설계 — 상태 머신·정규화·인덱스', 'DESIGN', 405, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '음식 배달 플랫폼 설계 — 주문·배차·ETA·실시간 추적', 'DESIGN', 406, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '트랜잭션 경계 코드 리뷰 — @Transactional 함정·자기호출·외부 호출', 'REVIEW', 407, false, NULL),
  (gen_random_uuid(), 'CS', '동적 계획법 실전 — 배낭·구간 DP·상태 설계', 'CONCEPT', 408, false, NULL),
  -- ── 45주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '음식 배달 면접 — 3자 상태 동기화·ETA·피크 부하 압박', 'INTERVIEW', 409, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '실시간 위치 추적·ETA 설계 — geospatial·지도 매칭·도착 예측', 'DESIGN', 410, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '외부 연동 게이트웨이 — ACL·회로차단·계약·재시도 설계', 'DESIGN', 411, false, NULL),
  (gen_random_uuid(), 'DATABASE', '풀필먼트 재고 모델 설계 — 다중 창고·예약·가용 재고 산정', 'DESIGN', 412, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '물류 허브·라우팅 설계 — 분류·배차·경로 최적화·SLA', 'DESIGN', 413, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'JPA 매핑·영속성 코드 리뷰 — 양방향 연관·Cascade·OSIV·equals', 'REVIEW', 414, false, NULL),
  (gen_random_uuid(), 'INFRA', '멀티리전 배포 파이프라인 설계 — GitOps·프로그레시브 딜리버리·리전 페일오버', 'DESIGN', 415, false, NULL),
  -- ── 46주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '물류 허브 라우팅 면접 — 처리량·SLA·장애 격리 압박', 'INTERVIEW', 416, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '풀필먼트 정산 시스템 설계 — 보관료·수수료·정산 주기', 'DESIGN', 417, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '오픈 API 플랫폼 설계 — 파트너 API·쿼터·키·버전 관리', 'DESIGN', 418, false, NULL),
  (gen_random_uuid(), 'DATABASE', '라스트마일 배차 데이터 모델 설계 — 기사·차량·경로·시간창', 'DESIGN', 419, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '주식 거래소 매칭엔진 설계 — 오더북·매칭·낮은 지연·시퀀싱', 'DESIGN', 420, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', 'API 구현 코드 리뷰 — Bean Validation·에러 응답·상태 코드·경계 검증', 'REVIEW', 421, false, NULL),
  (gen_random_uuid(), 'CS', '정보 이론 기초 — 엔트로피·해밍 거리·오류 검출 CRC', 'CONCEPT', 422, false, NULL),
  -- ── 47주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '미디어 파이프라인 — 트랜스코딩·ABR·HLS/DASH·프리페치', 'CONCEPT', 423, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '물류 예외·클레임 — 오배송·분실·파손·보상 SLA', 'CONCEPT', 424, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '외부 택배사 연동 장애 면접 — 타임아웃·재시도·정합성 압박', 'INTERVIEW', 425, false, NULL),
  (gen_random_uuid(), 'DATABASE', '마이그레이션·DDL 안전성 체크리스트 — 락·백필·롤백·배포 순서', 'REVIEW', 426, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '동영상 스트리밍 설계 — 트랜스코딩·ABR·CDN·조회수 집계', 'DESIGN', 427, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '배치·대량 처리 코드 리뷰 — 청크·메모리·트랜잭션·재시작·멱등', 'REVIEW', 428, false, NULL),
  (gen_random_uuid(), 'INFRA', '플랫폼 엔지니어링 — 내부 개발자 플랫폼(IDP)·골든패스·셀프서비스', 'CONCEPT', 429, false, NULL),
  -- ── 48주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '동영상 스트리밍 면접 — CDN 비용·트랜스코딩 지연·확장 압박', 'INTERVIEW', 430, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '실시간 시스템 면접 — 배차·추적·ETA 확장성', 'INTERVIEW', 431, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '아키텍처 의사결정 기록 — ADR·트레이드오프·거버넌스', 'CONCEPT', 432, false, NULL),
  (gen_random_uuid(), 'DATABASE', '물류 재고 정합성 면접 — 원장·이중 차감·보상·멱등 방어', 'INTERVIEW', 433, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '라이브 스트리밍 심화 — RTMP·저지연 HLS·WebRTC·Fan-out', 'CONCEPT', 434, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '예외·로깅 코드 리뷰 — 예외 삼킴·컨텍스트·PII 마스킹·재시도 분류', 'REVIEW', 435, false, NULL),
  (gen_random_uuid(), 'CS', '동시성 이론 심화 면접 — 메모리 모델·락프리·ABA 압박', 'INTERVIEW', 436, false, NULL),
  -- ── 49주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '파일 저장·동기화 설계 — 청킹·델타 싱크·메타데이터·충돌', 'DESIGN', 437, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '편의점 택배·픽업 네트워크 설계 — C2C·무인함·반품', 'DESIGN', 438, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '반품·환불 워크플로 — 보상·역물류·상태머신 설계', 'DESIGN', 439, false, NULL),
  (gen_random_uuid(), 'DATABASE', '대용량 트래킹 저장 면접 — 10억 이벤트 스키마·조회 방어', 'INTERVIEW', 440, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '웹 크롤러 설계 — Frontier·정중함·중복 URL·재방문 스케줄', 'DESIGN', 441, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '물류 재고·주문 구현 면접 — 오버셀·중복 주문·보상 시나리오 압박', 'INTERVIEW', 442, false, NULL),
  (gen_random_uuid(), 'INFRA', 'Kafka 클러스터 운영 설계 — 사이징·파티션 재배치·무중단 업그레이드', 'DESIGN', 443, false, NULL),
  -- ── 50주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', 'CRDT·OT 심화 — 수렴·G/PN-Counter·OR-Set·오프라인 병합', 'CONCEPT', 444, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '크로스보더 풀필먼트 설계 — 통관·다국가 재고·환적', 'DESIGN', 445, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '분산 아키텍처 안티패턴 — 분산 모놀리스·채터링·공유 DB', 'CONCEPT', 446, false, NULL),
  (gen_random_uuid(), 'DATABASE', '스키마 진화·마이그레이션 면접 — 무중단·롤백·호환성 방어', 'INTERVIEW', 447, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '협업 문서 편집 설계 — OT vs CRDT·커서·오프라인 병합', 'DESIGN', 448, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '외부 연동 장애 대응 면접 — 타임아웃·재시도·서킷·데이터 정합성', 'INTERVIEW', 449, false, NULL),
  (gen_random_uuid(), 'CS', '물류 알고리즘 응용 면접 — 빈패킹·경로·스케줄링 압박', 'INTERVIEW', 450, false, NULL),
  -- ── 51주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '대규모 조회수·카운터 — 분산 카운터·근사·집계·중복 제거', 'CONCEPT', 451, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '물류 관측성 — 추적성·이벤트 감사·SLA 모니터링', 'CONCEPT', 452, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '모놀리스 분해 전략 면접 — 경계·순서·리스크 압박', 'INTERVIEW', 453, false, NULL),
  (gen_random_uuid(), 'DATABASE', '복제·읽기 일관성 면접 — 복제 지연·라우팅·페일오버 방어', 'INTERVIEW', 454, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '알림 시스템 설계 — Fan-out·채널·우선순위·Dedup·Opt-out', 'DESIGN', 455, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '구현 설계 화이트보드 면접 — API·데이터 모델·경계·확장 압박', 'INTERVIEW', 456, false, NULL),
  (gen_random_uuid(), 'INFRA', '인프라 설계 면접 — 물류 대규모 트래픽·멀티리전·장애 격리 압박', 'INTERVIEW', 457, false, NULL),
  -- ── 52주차 (케이스·면접) ──
  (gen_random_uuid(), 'SYSTEM_DESIGN', '분산 작업 스케줄러 설계 — Cron·지연 큐·중복 방지·재시도', 'DESIGN', 458, false, NULL),
  (gen_random_uuid(), 'LOGISTICS', '물류 플랫폼 종합 면접 — 아키텍처·정합성·확장성 총정리', 'INTERVIEW', 459, false, NULL),
  (gen_random_uuid(), 'BACKEND_ARCHITECTURE', '커머스 플랫폼 아키텍처 종합 면접 — 경계·정합성·확장 압박', 'INTERVIEW', 460, false, NULL),
  (gen_random_uuid(), 'DATABASE', '실시간 데이터 모델링 면접 — 요구사항→ERD→인덱스 설계 방어', 'INTERVIEW', 461, false, NULL),
  (gen_random_uuid(), 'SYSTEM_DESIGN', '종합 압박 면접 — 요구사항 역질문·추정·Trade-off 방어 마스터리', 'INTERVIEW', 462, false, NULL),
  (gen_random_uuid(), 'BACKEND_DEV', '대용량 처리·배치 구현 면접 — 처리량·멱등·부분 실패·재처리 압박', 'INTERVIEW', 463, false, NULL),
  (gen_random_uuid(), 'CS', 'CS 종합 심화 면접 — OS·네트워크·자료구조 연결 압박', 'INTERVIEW', 464, false, NULL);
